config/routes.rb
Rails.application.routes.draw do

	post '/pages/uploadimages' => "pages#upload_image"
	post '/pages/deleteimage' => "pages#delete_image"

	post '/templates/uploadimages' => "templates#upload_image"
	post '/templates/deleteimage' => "templates#delete_image"

	get '/templates/:id/preview' => "templates#show_preview", as: :template_preview
	get '/templates/:id/remote_storage'  => "templates#get_remote"
	post '/templates/:id/remote_storage' => "templates#store_remote"
  	post '/templates/:id/save' => "templates#store_template", as: :save_template

  	resources :templates
  	
  	resources :sites do
		get '/pages/:id/preview' => "pages#show_preview", as: :show_preview
		get '/pages/:id/template' =>  "pages#get_template", as: :get_page
		post '/pages/:id/template' =>  "pages#store_template", as: :save_page
		get '/pages/:id/remote_storage'  => "pages#get_remote"
		post '/pages/:id/remote_storage' => "pages#store_remote"
	  	resources :pages
	end

	devise_for :users

	get 'home/index'

	root :to => "home#index"
end

app/views/templates/_form.html.erb
<%= form_with(model: template, local: true) do |form| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :template_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
/* Template edit */

app/views/templates/index.html.erb
<%= render :partial => 'layouts/navbar' %>
<div class="container">
<!-- <p id="notice"><%= notice %></p> -->

<h1>Templates</h1>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Created At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each_with_index do |template, id| %>
      <tr>
        <td><%= id+1 %></td>
        <td><%= template.name %></td>
        <td><%= template.created_at.strftime("%d-%b-%Y") %></td>
        <td><%= link_to 'Show', template_preview_path(template), :class => 'btn btn-primary btn-xs' %>
        <%= link_to 'Edit', template_path(template), :class => 'btn btn-primary btn-xs' %>
        <%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_template_path %>

</div>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<%= render :partial => 'layouts/extra' %>
<div id="gjs">
</div>
<script type="text/javascript">

var images = [];
<%= raw(@images.to_json) %>.forEach(function(e){
  images.push({src: "/templates/images/" + (e.id+"_"+ e.image_file_name).toString()});
});

var id = '<%= params[:id] %>';
var remote_store_url = '/templates/'+id+'/remote_storage';
var remote_load_url = '/templates/'+id+'/remote_storage';
var template_store_url = "<%= save_template_path(params[:id]) %>";
var image_upload_url = '/templates/uploadimages?template_id='+'<%= @template_id %>';
var image_delete_url = "/templates/deleteimage";
grape_view();
</script>

app/views/templates/show_preview.html.erb
<title><%= @template.name %></title>
<%= @template.template.html_safe if @template.template %>