config/routes.rb
Rails.application.routes.draw do

	post '/pages/uploadimages' => "pages#upload_image"
	post '/pages/deleteimage' => "pages#delete_image"

	post '/templates/uploadimages' => "templates#upload_image"
	post '/templates/deleteimage' => "templates#delete_image"

	get '/templates/:id/preview' => "templates#show_preview", as: :template_preview
	get '/templates/:id/remote_storage'  => "templates#get_remote"
	post '/templates/:id/remote_storage' => "templates#store_remote"
  	post '/templates/:id/save' => "templates#store_template", as: :save_template

  	resources :templates
  	
  	resources :sites do
		get '/pages/:id/preview' => "pages#show_preview", as: :show_preview
		get '/pages/:id/template' =>  "pages#get_template", as: :get_page
		post '/pages/:id/template' =>  "pages#store_template", as: :save_page
		get '/pages/:id/remote_storage'  => "pages#get_remote"
		post '/pages/:id/remote_storage' => "pages#store_remote"
	  	resources :pages
	end

	devise_for :users

	get 'home/index'

	root :to => "home#index"
end

app/views/pages/_form.html.erb
<%= form_with(model: [@site, @page], local: true) do |form| %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :page_name %>
  </div>
    
  <%= form.hidden_field :site_id, :value => params[:site_id] %>  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<%= render :partial => 'layouts/navbar' %>
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Page List</h1>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Created At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each_with_index do |page, id| %>
      <tr>
        <td><%= id+1 %></td>
        <td><%= page.name %></td>
        <td><%= page.created_at.strftime("%d-%b-%Y") %></td>
        <td><%= link_to 'Preview', site_show_preview_path(params[:site_id], page), :class => 'btn btn-primary btn-xs' %>
        <%= link_to 'Edit', site_page_path(params[:site_id], page), :class => 'btn btn-primary btn-xs' %>
        <!-- <%= link_to 'Edit', edit_site_page_path(params[:site_id], page), :class => 'btn btn-primary btn-xs' %> -->
        <%= link_to 'Destroy', site_page_path(params[:site_id], page), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New page', new_site_page_path(params[:site_id]) %>
</div>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', site_pages_path %>

app/views/pages/show.html.erb
<%= render :partial => 'layouts/extra' %>
<div id="gjs">
</div>
<script type="text/javascript">

  // Link Pages ( linkto is used in grape.min.js at line 12395 )
  var linkto = [{value: "", name: "Link template"}]; //Initialize linkto
  <%=raw @linkto.to_json %>.forEach(function(e){
    linkto.push({value: "/sites/"+e.site_id+"/pages/"+e.id+"/preview", name: e.name});
  });

  var images = [];
  <%= raw(@images.to_json) %>.forEach(function(e){
    images.push({src: "/images/" + (e.id+"_"+ e.image_file_name).toString()});
  });

  var site_id = '<%= params[:site_id] %>';
  var id = '<%= params[:id] %>';
  var remote_store_url = '/sites/'+site_id+'/pages/'+id+'/remote_storage';
  var remote_load_url = '/sites/'+site_id+'/pages/'+id+'/remote_storage';
  var template_store_url = "<%= site_save_page_path(params[:site_id], params[:id]) %>";
  var image_upload_url = '/pages/uploadimages?page_id='+'<%= @page_id %>';
  var image_delete_url = '/pages/deleteimage';
  grape_view();
</script>

app/views/pages/show_preview.html.erb
<title><%= @page.name %></title>
<%= @page.template.html_safe if @page.template %>