config/routes.rb
Rails.application.routes.draw do

	post '/pages/uploadimages' => "pages#upload_image"
	post '/pages/deleteimage' => "pages#delete_image"

	post '/templates/uploadimages' => "templates#upload_image"
	post '/templates/deleteimage' => "templates#delete_image"

	get '/templates/:id/preview' => "templates#show_preview", as: :template_preview
	get '/templates/:id/remote_storage'  => "templates#get_remote"
	post '/templates/:id/remote_storage' => "templates#store_remote"
  	post '/templates/:id/save' => "templates#store_template", as: :save_template

  	resources :templates
  	
  	resources :sites do
		get '/pages/:id/preview' => "pages#show_preview", as: :show_preview
		get '/pages/:id/template' =>  "pages#get_template", as: :get_page
		post '/pages/:id/template' =>  "pages#store_template", as: :save_page
		get '/pages/:id/remote_storage'  => "pages#get_remote"
		post '/pages/:id/remote_storage' => "pages#store_remote"
	  	resources :pages
	end

	devise_for :users

	get 'home/index'

	root :to => "home#index"
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user
  has_many :pages, dependent: :destroy
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.where(user_id: current_user)
  end

  # GET /sites/1
  # GET /sites/1.json
  def show    
    @pages = Page.where(site_id: params[:id])
  end

  # GET /sites/new
  def new
    @site = Site.new
    @templates = Template.all.select("id", "name");    
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)
    @site.user_id = current_user.id
    template_id = params[:site][:template_id]
    unless(template_id.nil? || template_id.empty?)
      template = Template.find(template_id)
      @page = Page.new
      @page.site = @site
      @page.name = "Page1"
      @page.template = template.template
      @page.remote_storage = template.remote_storage

      @page.save!

    end

    respond_to do |format|
      if @site.save
        format.html { redirect_to site_pages_path(@site), notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  # def update
  #   respond_to do |format|
  #     if @site.update(site_params)
  #       format.html { redirect_to @site, notice: 'Site was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @site }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @site.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_with(model: site, local: true) do |form| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :site_name %>
  </div>  

  <%= form.label :template_id, :class => '' %>
  <%= form.select("template_id", @templates.collect {|x| [x.name, x.id] }, {:include_blank => "Choose Custom Template"}, {:class => ''}) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<%= render :partial => 'layouts/navbar' %>
<div class="container">
<!-- <p id="notice"><%= notice %></p> -->

<h1>My Sites</h1>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Created At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each_with_index do |site, id| %>
      <tr>
        <td><%= id+1 %></td>
        <td><%= site.name %></td>
        <td><%= site.created_at.strftime("%d-%b-%Y") %></td>
        <td><%= link_to 'Show', site_pages_path(site), :class => 'btn btn-primary btn-xs' %>
        <!-- <%= link_to 'Edit', site_pages_path(site), :class => 'btn btn-primary btn-xs' %> -->
        <!-- <%= link_to 'Edit', edit_site_path(site), :class => 'btn btn-primary btn-xs' %> -->
        <%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

</div>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<%= render :partial => 'layouts/navbar' %>
<div class="container">
<!-- <p id="notice"><%= notice %></p> -->

<h1>Pages</h1>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Created At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each_with_index do |page, id| %>
      <tr>
        <td><%= id+1 %></td>
        <td><%= page.name %></td>
        <td><%= page.created_at.strftime("%d-%b-%Y") %></td>
        <td><%= link_to 'Show', site_page_path(params[:id]), :class => 'btn btn-primary btn-xs' %>
        <%= link_to 'Edit', edit_site_path(page), :class => 'btn btn-primary btn-xs' %>
        <%= link_to 'Destroy', site_path(params[:id]), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_site_path(:site_id => params[:id]) %>

</div>